//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTapManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish_Order
    {
        public int Id_Dish_Order { get; set; }
        public int Dish_id { get; set; }
        public int Order_Id { get; set; }
    
        public virtual Dish Dish { get; set; }
        public virtual Order Order { get; set; }
    }
}
