//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTapManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int ID_logs { get; set; }
        public System.DateTime Date_of_recording { get; set; }
        public System.TimeSpan Time_of_recording { get; set; }
        public int Booking_ID { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
