//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableTapManager.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetails
    {
        public int Id_Payment { get; set; }
        public int Payment_amount { get; set; }
        public System.DateTime Date_and_time_of_payment { get; set; }
        public string Payment_status { get; set; }
        public int Id_Order { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    }
}
